create extension if not exists pgcrypto;

create table if not exists public.ar_scenes (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  public_url text,
  src text not null,
  assets jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  trigger jsonb not null default '{"type":"qr"}'::jsonb,
  claim_limit integer not null default 0 check (claim_limit >= 0),
  sqr_link_id text,
  sqr_qr_id text,
  sqr_short_url text,
  sqr_qr_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ar_events (
  id bigint generated by default as identity primary key,
  scene_slug text not null references public.ar_scenes(slug) on delete cascade,
  event_type text not null,
  meta jsonb not null default '{}'::jsonb,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.ar_claims (
  id bigint generated by default as identity primary key,
  scene_slug text not null references public.ar_scenes(slug) on delete cascade,
  device_token text not null,
  created_at timestamptz not null default now(),
  unique(scene_slug,device_token)
);

create index if not exists ar_events_scene_created_idx on public.ar_events(scene_slug,created_at desc);
create index if not exists ar_claims_scene_idx on public.ar_claims(scene_slug);

alter table public.ar_scenes enable row level security;
alter table public.ar_events enable row level security;
alter table public.ar_claims enable row level security;

-- Serverless functions use SUPABASE_SERVICE_ROLE_KEY and bypass RLS.
-- No public table policies are intentionally created for the MVP.

-- Create a public storage bucket named `ar-assets` in Supabase Storage.
-- The serverless upload-url endpoint mints one-time signed upload tokens,
-- so anonymous users do not need broad write access to the bucket.
