create extension if not exists pgcrypto;

create table if not exists public.ar_scenes (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  public_url text,
  src text,
  assets jsonb not null default '[]'::jsonb,
  objects jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  trigger jsonb not null default '{"type":"qr"}'::jsonb,
  hunt jsonb not null default '{"enabled":false}'::jsonb,
  claim_limit integer not null default 0 check (claim_limit >= 0),
  sqr_link_id text,
  sqr_qr_id text,
  sqr_short_url text,
  sqr_qr_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ar_scenes add column if not exists description text not null default '';
alter table public.ar_scenes add column if not exists objects jsonb not null default '[]'::jsonb;
alter table public.ar_scenes add column if not exists hunt jsonb not null default '{"enabled":false}'::jsonb;
alter table public.ar_scenes alter column src drop not null;

create table if not exists public.ar_assets (
  id uuid primary key default gen_random_uuid(),
  scene_slug text references public.ar_scenes(slug) on delete cascade,
  object_id text,
  kind text not null check (kind in ('model','image','video','audio','other')),
  storage_path text,
  public_url text,
  mime_type text,
  size_bytes bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ar_anchors (
  id uuid primary key default gen_random_uuid(),
  scene_slug text not null references public.ar_scenes(slug) on delete cascade,
  object_id text not null,
  anchor_type text not null check (anchor_type in ('scene','gps','image','qr','spatial')),
  latitude double precision,
  longitude double precision,
  altitude double precision,
  accuracy_meters double precision,
  target text,
  transform jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(scene_slug,object_id)
);

create table if not exists public.ar_events (
  id bigint generated by default as identity primary key,
  scene_slug text not null references public.ar_scenes(slug) on delete cascade,
  event_type text not null,
  meta jsonb not null default '{}'::jsonb,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.ar_claims (
  id bigint generated by default as identity primary key,
  scene_slug text not null references public.ar_scenes(slug) on delete cascade,
  device_token text not null,
  created_at timestamptz not null default now(),
  unique(scene_slug,device_token)
);

create index if not exists ar_events_scene_created_idx on public.ar_events(scene_slug,created_at desc);
create index if not exists ar_claims_scene_idx on public.ar_claims(scene_slug);
create index if not exists ar_assets_scene_idx on public.ar_assets(scene_slug);
create index if not exists ar_anchors_scene_idx on public.ar_anchors(scene_slug);
create index if not exists ar_anchors_geo_idx on public.ar_anchors(latitude,longitude);

create or replace function public.claim_ar_collectible(p_scene_slug text, p_device_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer;
  v_count integer;
  v_existing boolean;
begin
  perform pg_advisory_xact_lock(hashtext(p_scene_slug));
  select claim_limit into v_limit from ar_scenes where slug=p_scene_slug for update;
  if not found then raise exception 'Scene not found'; end if;
  if coalesce(v_limit,0) <= 0 then raise exception 'Claims are disabled for this scene'; end if;
  select exists(select 1 from ar_claims where scene_slug=p_scene_slug and device_token=p_device_token) into v_existing;
  select count(*) into v_count from ar_claims where scene_slug=p_scene_slug;
  if v_existing then return jsonb_build_object('duplicate',true,'remaining',greatest(0,v_limit-v_count)); end if;
  if v_count >= v_limit then raise exception 'All collectibles have been claimed'; end if;
  insert into ar_claims(scene_slug,device_token) values(p_scene_slug,p_device_token);
  insert into ar_events(scene_slug,event_type,meta) values(p_scene_slug,'claim','{}'::jsonb);
  return jsonb_build_object('duplicate',false,'remaining',greatest(0,v_limit-v_count-1));
end;
$$;

alter table public.ar_scenes enable row level security;
alter table public.ar_assets enable row level security;
alter table public.ar_anchors enable row level security;
alter table public.ar_events enable row level security;
alter table public.ar_claims enable row level security;

-- Serverless functions use SUPABASE_SERVICE_ROLE_KEY and bypass RLS.
-- Create a public Storage bucket named `ar-assets` for GLB and future media assets.
-- `ar_anchors` stores GPS now and image/QR/spatial anchor payloads as those engines are enabled.
