create table if not exists public.ar_integrations (
  id uuid primary key default gen_random_uuid(),
  scene_slug text references public.ar_scenes(slug) on delete cascade,
  provider text not null,
  config jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ar_event_deliveries (
  id bigint generated by default as identity primary key,
  event_id bigint references public.ar_events(id) on delete cascade,
  integration_id uuid references public.ar_integrations(id) on delete cascade,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists ar_integrations_scene_idx on public.ar_integrations(scene_slug);
create index if not exists ar_event_deliveries_status_idx on public.ar_event_deliveries(status,created_at);

alter table public.ar_integrations enable row level security;
alter table public.ar_event_deliveries enable row level security;
